<template>
  <div class="whitepaper-reader h-full flex flex-col bg-slate-50 relative animate-fade-in pb-10 overflow-y-auto">
    
    <!-- Top Action Bar -->
    <div class="sticky top-0 z-20 bg-white/80 backdrop-blur border-b border-slate-200 px-6 py-4 flex justify-between items-center shadow-sm">
      <h2 class="text-xl font-bold flex items-center text-slate-800">
        <el-icon class="mr-2 text-blue-600"><DocumentChecked /></el-icon>
        卧龙·破局行动白皮书
      </h2>
      <div class="space-x-4">
        <el-button @click="openReasoningDialog" plain>查看思维链</el-button>
        <el-button @click="backToWorkflow">返回工作流</el-button>
        <el-button type="primary" :loading="isExporting" @click="exportPdf" icon="Download">
          导出 PDF 报告
        </el-button>
      </div>
    </div>

    <!-- Main Content for Export -->
    <div 
      class="flex-1 w-full max-w-4xl mx-auto mt-8 bg-white shadow-lg p-8 md:p-12 rounded-sm print-container relative min-h-[800px]"
      ref="printAreaRef"
    >
      <div v-if="isLoading" class="absolute inset-0 bg-white/50 backdrop-blur-sm z-10 flex flex-col items-center justify-center">
        <el-icon class="is-loading text-4xl text-blue-500 mb-4"><Loading /></el-icon>
        <p class="text-slate-500">正在凝练全维行动总纲...</p>
      </div>

      <div v-else-if="whitepaperData">
        <!-- Header -->
        <div class="border-b-4 border-slate-800 pb-6 mb-8 text-center">
          <h1 class="text-4xl font-extrabold text-slate-900 tracking-tight">卧龙决策系统</h1>
          <p class="text-slate-500 mt-2 font-mono uppercase tracking-widest text-sm">Action Strategy Whitepaper | {{ caseStore.currentCaseId }}</p>
        </div>

        <!-- Section 1: Core Conflict -->
        <section class="mb-12">
          <ConflictCard 
            :main-conflict="whitepaperData.main_conflict"
            :critical-warnings="whitepaperData.critical_warnings"
          />
        </section>

        <!-- Section 1.5: Contradiction Transformation -->
        <section class="mb-12" v-if="whitepaperData.contradiction_transformation">
          <h3 class="text-xl font-bold text-slate-800 mb-4 flex items-center">
            <el-icon class="mr-2 text-amber-500"><Sort /></el-icon>
            矛盾转化路径
          </h3>
          <div class="bg-amber-50 border border-amber-100 rounded-lg p-5 space-y-3 text-sm">
            <div class="text-slate-700">
              <span class="font-bold text-amber-700">触发条件：</span>
              <span>{{ whitepaperData.contradiction_transformation.trigger_condition || '—' }}</span>
            </div>
            <div class="text-slate-700">
              <span class="font-bold text-amber-700">次生主要矛盾：</span>
              <span>{{ whitepaperData.contradiction_transformation.next_stage_contradiction || '—' }}</span>
            </div>
            <div class="text-slate-700">
              <span class="font-bold text-amber-700">辩证洞察：</span>
              <span>{{ whitepaperData.contradiction_transformation.dialectical_insight || '—' }}</span>
            </div>
          </div>
        </section>

        <!-- Section 2: Unknowns -->
        <section class="mb-12" v-if="whitepaperData.unknowns?.length">
          <h3 class="text-xl font-bold text-slate-800 mb-4 flex items-center">
            <el-icon class="mr-2 text-indigo-500"><QuestionFilled /></el-icon>
            核心未知数验证池
          </h3>
          <div class="bg-indigo-50 border border-indigo-100 rounded-lg p-5">
            <ul class="list-disc pl-5 space-y-2 text-indigo-900">
              <li v-for="(u, idx) in whitepaperData.unknowns" :key="idx">{{ u }}</li>
            </ul>
          </div>
        </section>

        <!-- Section 3: MVP Actions -->
        <section class="mb-12">
          <h3 class="text-xl font-bold text-slate-800 mb-4 flex items-center">
            <el-icon class="mr-2 text-green-600"><Checked /></el-icon>
            最小可行性闭环测试 (MVP Actions)
          </h3>
          <ActionList :actions="whitepaperData.mvp_actions" @feedback="handleFeedback" />
        </section>

        <!-- Footer -->
        <div class="mt-20 pt-8 border-t border-slate-100 text-center text-slate-400 text-xs flex flex-col items-center space-y-2">
          <el-icon class="text-2xl text-slate-200"><Odometer /></el-icon>
          <p>This document is generated by Wolong Decision Support Engine.</p>
          <p>Stay Rational, Act Definite.</p>
        </div>
      </div>
    </div>

    <el-dialog v-model="showReasoningDialog" title="白皮书推理链" width="720px" :close-on-click-modal="false">
      <div class="space-y-3">
        <div class="bg-slate-50 border border-slate-200 rounded-lg p-3">
          <div class="text-xs font-bold text-slate-600 mb-1">推理摘要</div>
          <div class="text-sm text-slate-700 whitespace-pre-wrap">{{ reasoningText || '暂无推理摘要' }}</div>
        </div>
        <div class="bg-slate-50 border border-slate-200 rounded-lg p-3">
          <div class="text-xs font-bold text-slate-600 mb-1">结构化输出</div>
          <pre class="text-xs text-slate-700 whitespace-pre-wrap max-h-96 overflow-auto">{{ reasoningJson }}</pre>
        </div>
      </div>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { DocumentChecked, Loading, QuestionFilled, Checked, Odometer, Sort } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import html2canvas from 'html2canvas'
import { jsPDF } from 'jspdf'

import ConflictCard from '../components/ConflictCard.vue'
import ActionList from '../components/ActionList.vue'
import { getWhitepaper, submitWhitepaperFeedback } from '../api/case'
import { useCaseStore } from '../store/caseStore'

const router = useRouter()
const route = useRoute()
const caseStore = useCaseStore()
const caseId = route.params.id as string

const isLoading = ref(true)
const isExporting = ref(false)
const whitepaperData = ref<any>(null)
const printAreaRef = ref<HTMLElement | null>(null)
const showReasoningDialog = ref(false)
const reasoningText = ref('')
const reasoningJson = ref('')

onMounted(async () => {
  try {
    const res = await getWhitepaper(caseId)
    if (res.code === 200 && res.data?.model_generated !== false) {
      whitepaperData.value = res.data
    } else {
      ElMessage.error('白皮书未由模型成功生成，请返回世界线阶段重试')
    }
  } catch (err: any) {
    ElMessage.error(err?.response?.data?.detail || '无法读取白皮书数据')
  } finally {
    isLoading.value = false
  }
})

const handleFeedback = async (payload: any) => {
  try {
    const res = await submitWhitepaperFeedback(caseId, { ...payload, reason: '用户手动纠错', is_negative: true })
    if (res.code === 200) {
      ElMessage.success('已记录纠错，系统将在后续推演中矫正该偏差')
    }
  } catch (err) {
    ElMessage.error('反馈异常')
  }
}

const backToWorkflow = () => {
  router.push(`/case/${caseId}/workflow/sandbox`)
}

const openReasoningDialog = () => {
  if (!whitepaperData.value) {
    reasoningText.value = '当前尚未加载白皮书。'
    reasoningJson.value = '暂无数据'
    showReasoningDialog.value = true
    return
  }
  const raw = whitepaperData.value.raw_whitepaper
    || whitepaperData.value.system_deduction_snapshot
    || whitepaperData.value.generation_trace
    || whitepaperData.value
  reasoningText.value = [
    whitepaperData.value.main_conflict,
    ...(whitepaperData.value.critical_warnings || []),
  ].filter(Boolean).join('\n')
  reasoningJson.value = JSON.stringify(raw, null, 2)
  showReasoningDialog.value = true
}

const exportPdf = async () => {
  if (!printAreaRef.value) return
  isExporting.value = true
  
  try {
    // 1. Take snapshot of DOM
    const canvas = await html2canvas(printAreaRef.value, { scale: 2, useCORS: true })
    const imgData = canvas.toDataURL('image/jpeg', 1.0)
    
    // 2. Calculate PDF pages (A4 size)
    const pdf = new jsPDF('p', 'pt', 'a4')
    const pdfWidth = pdf.internal.pageSize.getWidth()
    const pdfHeight = (canvas.height * pdfWidth) / canvas.width
    
    // 3. Add Image
    pdf.addImage(imgData, 'JPEG', 0, 0, pdfWidth, pdfHeight)
    
    // 4. Save
    pdf.save(`Wolong_Whitepaper_${caseId}.pdf`)
    ElMessage.success('PDF 报表已保存')
  } catch (err) {
    ElMessage.error('PDF 生成失败')
  } finally {
    isExporting.value = false
  }
}
</script>

<style scoped>
.animate-fade-in {
  animation: fadeIn 0.4s ease-out;
}
@keyframes fadeIn {
  from { opacity: 0; transform: translateY(10px); }
  to { opacity: 1; transform: translateY(0); }
}
/* Ensure the exported document has a clean white background */
.print-container {
  background-color: #ffffff;
}
</style>
